Making sure unit tests work

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -27,12 +27,13 @@ jobs:
         run: |
           error=0
           for test in test/bin/*; do
-            success=$(valgrind --leak-check=full --error-exitcode=1 --show-leak-kinds=all --errors-for-leak-kinds=all $test)
-            if [ $? -ne 0 ]; then
-              error=1
-              echo $success
-            else
-              echo "Test $test passed"
-            fi
+          failure=$(valgrind --leak-check=full --error-exitcode=1 --show-leak-kinds=all --errors-for-leak-kinds=all $test 2>&1)
+          if [ $? -ne 0 ]; then
+            error=1
+            echo $failure
+            echo "Test $test failed"
+          else
+            echo "Test $test passed"
+          fi
           done
           exit $error
